import './ipcapis/ipcPlayListsApi'
import './ipcapis/ipcBilibiliApi'
import './ipcapis/emoMusicApi'
import './ipcapis/ipcAccountSettings'
import './ipcapis/ipcSettings'
import './ipcapis/ipcDesktopLyrics'